### ISSUE TITLE
Image Attachment of CZI is not read correctly with BioFormats 5.3.4

### ISSUE THREAD

**Issue by sebi06** [ome/bioformats#2791]
Hi,

some of our systems use a preview camera to acquire an overview image of the sample and/or carrier to use this for sample or sample carrier recognition. This image is stored as an attachment inside the CZI. When the respective option is activated using BioFormats 5.3.4 this image is read but only partially (see attached screenshots)

Maybe you read only 1 series of it? The image actually consist out of a few single images and is "tiles" together. Let me know if you need more detailed info or more testfiles to fix this

The original CZI image can be found here:

https://drive.google.com/open?id=0B8YXT9fyYIBzWEg5ZTl5ZDlQTDg

![attachment_czicomplete_zen](https://cloud.githubusercontent.com/assets/3833249/24092314/d89faa94-0d4d-11e7-9d2e-fa5f9bde4a40.png)
![attachment_part](https://cloud.githubusercontent.com/assets/3833249/24092313/d89dc198-0d4d-11e7-9b61-82eb0214a9b4.png)

**Comment by dgault** [comment]
Thank you for providing a sample file to test this with. I was able to reproduce the issue as described with the latest Bio-Formats build. I have added the details to card on the Bio-Formats Trello board to be prioritised.

**Comment by melissalinkert** [comment]
For reference, the Trello card is: https://trello.com/c/33ZpzJ9G/122-zeiss-czi-image-attachment-incorrect-width

**Comment by zeissmicroscopy** [comment]
I recreated the link with an example of an CZI with attachment:

https://drive.google.com/open?id=1LsM94JW2l_B9ElcxNlSVXLoztJwE6_kJ

**Comment by melissalinkert** [comment]
Thank you, @zeissmicroscopy.  The file has now been downloaded and copied to our testing repository (```inbox/gh-2791/```).

**Comment by melissalinkert** [comment]
Testing this file with https://github.com/ome/bioformats/pull/3681, ```showinf -option zeissczi.trim_dimensions true``` results in the correct image size.

**Comment by melissalinkert** [comment]
This was fixed in 6.7.0, as a result of the changes in https://github.com/ome/bioformats/pull/3687.
