### ISSUE TITLE
setting JPEG compression quality with bfconvert

### ISSUE THREAD

**Issue by ebremer** [ome/bioformats#3370]
Is there a undocumented command line option to set the JPEG compression quality with bfconvert?

**Comment by dgault** [comment]
Hi @ebremer, I'm afraid not, the list of compression options are limited to the below:

```
 * JPEG-2000: JPEG-2000 Lossy, JPEG-2000
 * OME-TIFF: Uncompressed, LZW, JPEG-2000, JPEG-2000 Lossy, JPEG, zlib
 * OME-XML: Uncompressed, zlib
 * QuickTime: Uncompressed
 * Tagged Image File Format: Uncompressed, LZW, JPEG-2000, JPEG-2000 Lossy, JPEG, zlib
```

**Comment by ebremer** [comment]
@dgault not the types of compression, but the sub-option of JPEG which sets the compression level, usually 0-100.  I've found this in the source
CodecOptions opt = new CodecOptions();
    opt.quality = 100.0;
but it doesn't seem accessible from bfconvert. In testing this, I uncovered: https://github.com/openmicroscopy/bioformats/issues/3372

**Comment by mtbc** [comment]
Not that this is also sought on [[image.sc] Bfconvert specify JPEG quality](https://forum.image.sc/t/27176).

**Comment by dgault** [comment]
A further request for this feature has been received on thread https://forum.image.sc/t/error-converting-large-images-to-ome-tiff-using-the-command-line-bioformats-tool-bfconvert/70243/6
