### ISSUE TITLE
NDPIReader.initStandardMetadata looping

### ISSUE THREAD

**Issue by mtbc** [ome/bioformats#3432]
The NDPI in `/uod/idr/scratch/inbox/ola-2019-09-06/` appears to cause https://github.com/ome/bioformats/blob/v6.2.1/components/formats-gpl/src/loci/formats/in/NDPIReader.java#L297 not to terminate. Perhaps the `if` condition is false. Reported in https://forum.image.sc/t/29273.

**Comment by melissalinkert** [comment]
Fixed by #3505, file added to test repo in https://github.com/openmicroscopy/data_repo_config/pull/442.
