### ISSUE TITLE
Is there a tutorial how to read and display an biftiff?

### ISSUE THREAD

**Issue by Samyssmile** [ome/bioformats#3434]
Is there a tutorial how to read and display an biftiff?

**Comment by dgault** [comment]
Hi @Samyssmile, are you using the Bio-Formats API directly or through the command line tools or FIJI?

If you are using the API directly then for larger images we would recommend tiled reading. You can see some example code for this in https://docs.openmicroscopy.org/bio-formats/6.2.1/developers/tiling.html

**Comment by Samyssmile** [comment]
tank you
