### ISSUE TITLE
Incorrect objective magnification reported for NDPI images

### ISSUE THREAD

**Issue by tfrikker-genedata** [ome/bioformats#3439]
The NDPIReader does not seem to return the correct magnification level of the source image.
Currently, it reads from the field "Objective.Lens.Magnificant" - I believe it should instead read this magnification from the SOURCE_LENS field (TIFF tag 65421), which is 
already used inside the NDPIReader.

More information on the magnification field can be found here:
https://openslide.org/formats/hamamatsu/

"openslide.objective-power": normalized hamamatsu.SourceLens

**Comment by sbesson** [comment]
Hi @tfrikker-genedata, thanks for starting the discussion. We are indeed using the `SourceLens` TIFF tag as indicated in the OpenSlide format page to differentiate the WSI image from the ancillary images. Reviewing the metadata from a few NDPI samples like [this ones](https://downloads.openmicroscopy.org/images/Hamamatsu-NDPI/manuel/test3-DAPI%202%20(387)%20.ndpi), I get:

```
Tag 65421: 40.000000
Tag 65421: 20.000000
Tag 65421: 10.000000
Tag 65421: 5.000000
Tag 65421: -2.000000
Tag 65421: -1.000000
Objective.Lens.Magnificant=35.16
```

As the OpenSlide page suggests, NDP.view also parses the source lens as `40x`. I opened a pull request to adjust the reader and parse the [NominalMagnification](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome.html#Objective_NominalMagnification) from the `SourceLens` tag while keeping the previous value stored as the [CalibratedMagnification](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Objective_CalibratedMagnification). Happy to hear any thought  on whether the second part is also a correct assumption.
