### ISSUE TITLE
Support for C#

### ISSUE THREAD

**Issue by ricklina90** [ome/bioformats#3457]
Hello,
          If I need to read image use C#, Can any one tell me any suggestion?

Thanks for your attention,
Rick

**Comment by sbesson** [comment]
Hi @ricklina90, OME does not develop or maintain a C# implementation of the Bio-Formats library. One  project that might be of interest for you to check is https://github.com/GDanovski/CellTool.

**Comment by ricklina90** [comment]
Hi@sbesson, Thanks for the quick reply.Very appreciated.

**Comment by BiologyTools** [comment]
I have created C# project which supports all BioFormats images thought I would post it here, if anyone is still looking for a solution. https://github.com/BiologyTools/BioGTK
