### ISSUE TITLE
JPEG codec broken (6.3.0)

### ISSUE THREAD

**Issue by ebremer** [ome/bioformats#3462]
bfconvert -series 2 -tilex 512 -tiley 512 -compression LZW image.vsi lzw.tif

Image looks like:
![image](https://user-images.githubusercontent.com/4094961/68145562-10e66f00-ff04-11e9-86fe-891c8c5e2100.png)

bfconvert -series 2 -tilex 512 -tiley 512 -compression JPEG image.vsi jpeg.tif

Image looks like:
![image](https://user-images.githubusercontent.com/4094961/68145604-2f4c6a80-ff04-11e9-841b-d6682ba68758.png)

**Comment by sbesson** [comment]
@ebremer I failed to reproduce the error you mentioned above using either RGB images or sample VSI files. In both cases JPEG-compressed or LZW-compressed TIFF looked identical after reopening. Do you have a sample file allowing to reproduce the issue?

**Comment by ebremer** [comment]
Let me try it on some other images.  The above image isn't something I can share at this time.

**Comment by ebremer** [comment]
I checked the JPG compressed image I created with showinf and it looks fine.  It doesn't look fine in GIMP, Photoshop, nor windows image viewer.  GIMP actually reports "Improper JPEG sampling factors 2,2.  Apparently should be 1,1.

**Comment by ebremer** [comment]
I also tried this on some random images that came out of vips and the command will work for LZW creating viewable images in all programs, but using JPEG will make images only viewable in showinf.

**Comment by ebremer** [comment]
Try using https://upload.wikimedia.org/wikipedia/commons/2/2d/Chameleons_Large_Image.jpg
with:
bfconvert -series 0 -compression JPEG -tilex 256 -tiley 256 cham.jpg boo.tif
and
bfconvert -series 0 -compression LZW -tilex 256 -tiley 256 cham.jpg boo.tif

both will be viewable in showinf, but only LZW works with other programs like Photoshop and GIMP, but the JPEG compression will fail in non-showinf programs.

**Comment by sbesson** [comment]
Thanks for the additional troubleshooting, it feels like this is the same underlying problem as the one reported in https://github.com/ome/bioformats/issues/3372. Proposing to close this as duplicate and stick to the former issue for tracking this bug.

**Comment by ebremer** [comment]
Okay.
