### ISSUE TITLE
Weird section of code in ImageConverter

### ISSUE THREAD

**Issue by ebremer** [ome/bioformats#3512]
What is going on here?
https://github.com/ome/bioformats/blob/fc5c23e3907d6c9b3893f52eab54996d1c77ec22/components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java#L581-L598

The only part that seems to change is:
if (autoscale) {
              store.setPixelsType(PixelType.UINT8, i);
 }

Everything else is hard-coded for zero.  The other lines seems to be doing nothing except keep resetting the same values.

**Comment by dgault** [comment]
Good spot, that looks like a bug and the other values should indeed be `meta.setPixelsSizeC(new PositiveInteger(1), i); ` etc

That section of code is supposed to be overwriting the reader metadata when you are converting only a single timepoint or a single channel. So if you are only converting a single timepoint, then for each series the sizeT of the output will be overwritten to 1.

I will test a fix in the next day or two and try to open a PR to get this resolved for the next release.
