### ISSUE TITLE
Issue with .vsi-files in QuPath

### ISSUE THREAD

**Issue by TMM-98** [ome/bioformats#3533]
Hello there,

QuPath won't open my .vsi-images, which is a unique Olympus CellSens File-format.

Interestingly, Fiji is able to open these files with the bioformat-plugin, so, as the supported formats are same, I do not quite understand the reason. The Error Report is subsequently attached
Does anyone have any idea on how to solve this issue?

Thank you so much in advance!
Thiemo

![Screen Shot 2020-03-23 at 5 29 40 PM](https://user-images.githubusercontent.com/62424344/77339481-20881800-6d2c-11ea-8b36-b293aabedd63.png)

**Error Report:**
WARN: Unable to open /Volumes/LACIE SHARE/Doktorarbeit/Projekt_HIFLO/Demyelinisierung/APC/Alt2.vsi with OpenSlide: /Volumes/LACIE SHARE/Doktorarbeit/Projekt_HIFLO/Demyelinisierung/APC/Alt2.vsi: Not a file that OpenSlide can recognize
WARN: Error opening /Volumes/LACIE SHARE/Doktorarbeit/Projekt_HIFLO/Demyelinisierung/APC/Alt2.vsi with ImageJ: Could not open /Volumes/LACIE SHARE/Doktorarbeit/Projekt_HIFLO/Demyelinisierung/APC/Alt2.vsi with ImageJ
ERROR: Unable to build whole slide server - check your classpath for a suitable library (e.g. OpenSlide, BioFormats)
	
ERROR: /Applications/QuPath.app/Contents/Java/QuPathApp.jar:qupath/qupath-core-0.1.2.jar:qupath/qupath-core-awt-0.1.2.jar:qupath/qupath-core-processing-0.1.2.jar:qupath/qupath-core-processing-awt-0.1.2.jar:qupath/qupath-extension-ij-0.1.2.jar:qupath/qupath-extension-input-0.1.2.jar:qupath/qupath-extension-opencv-0.1.2.jar:qupath/qupath-extension-openslide-0.1.2.jar:qupath/qupath-extension-pen-0.1.2.jar:qupath/qupath-extension-script-editor-0.1.2.jar:qupath/qupath-gui-fx-0.1.2.jar:qupath/qupath-processing-ij-0.1.2.jar:qupath/qupath-processing-opencv-0.1.2.jar:jars/commons-math3-3.6.1.jar:jars/controlsfx-8.40.12.jar:jars/flowless-0.4.5.jar:jars/groovy-2.4.7.jar:jars/groovy-jsr223-2.4.7.jar:jars/gson-2.8.0.jar:jars/ij-1.51g.jar:jars/jfxtras-common-8.0-r5.jar:jars/jfxtras-menu-8.0-r5.jar:jars/jinput-2.0.6.jar:jars/jpen-2-150301.jar:jars/jutils-1.0.0.jar:jars/logback-classic-1.1.7.jar:jars/logback-core-1.1.7.jar:jars/opencv-3.1.0.jar:jars/openslide-3.4.1_2.jar:jars/packager.jar:jars/reactfx-2.0-M4u1.jar:jars/richtextfx-0.6.10.jar:jars/slf4j-api-1.7.20.jar:jars/undofx-1.2.jar:jars/wellbehavedfx-0.1.1.jar:QuPathApp.jar
ERROR: Open image: Sorry, I can't open /Volumes/LACIE SHARE/Doktorarbeit/Projekt_HIFLO/Demyelinisierung/APC/Alt2.vsi

![image](https://user-images.githubusercontent.com/62424344/77339884-c2a80000-6d2c-11ea-98cb-0463e8957ec7.png)

**Comment by melissalinkert** [comment]
It looks like you are using QuPath 0.1.2, which does not have Bio-Formats installed by default.  Do you have the Bio-Formats extension (https://github.com/qupath/qupath-bioformats-extension) installed?  If not, does installing that extension solve the problem?

**Comment by petebankhead** [comment]
If you want to open the image with QuPath v0.1.2, you do indeed need the Bio-Formats extension. Documentation is [here](https://github.com/qupath/qupath/wiki/Supported-image-formats).

However, I'd recommend trying the latest milestone release of QuPath from https://github.com/qupath/qupath/releases - this may already have resolved any issues you see (in which case *don't* install the Bio-Formats extension - it isn't needed and isn't compatible with v0.2.0). Documentation for it is [here](https://qupath.readthedocs.io/en/latest/docs/intro/formats.html).

I hope that a stable version of v0.2.0 will be available within the next month or so.

If Fiji can open the image with Bio-Formats, it is unlikely to be an issue with Bio-Formats. The [image.sc discussion](https://forum.image.sc/t/importing-a-vsi-composite-image-in-imagej-via-bioformats-plugin-how-do-i-get-a-high-resolution-macro-image/35282) is probably a better place to follow up.

**Comment by sbesson** [comment]
Closing and using the image.sc thread as the single place of discussion as per https://forum.image.sc/t/importing-a-vsi-composite-image-in-imagej-via-bioformats-plugin-how-do-i-get-a-high-resolution-macro-image/35282/7
