### ISSUE TITLE
Conversion of OME Creator attribute

### ISSUE THREAD

**Issue by sbesson** [ome/bioformats#3541]
The  [6.1.0 release of ome-model](https://github.com/ome/ome-model/blob/v6.1.0/NEWS.md) includes proper support for the `OME/Creator` attribute in the `ome.xml.meta` interfaces and implementations.

Inline with the [OME schema](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#OME_Creator), the OME-XML and OME-TIFF writers unconditionally populate this attribute with the version of Bio-Formats.

https://github.com/ome/bioformats/blob/b1be2a9baa7b780ca258315d80132479099c57de/components/formats-bsd/src/loci/formats/out/OMETiffWriter.java#L297-L299

https://github.com/ome/bioformats/blob/b1be2a9baa7b780ca258315d80132479099c57de/components/formats-bsd/src/loci/formats/out/OMETiffWriter.java#L320-L322

https://github.com/ome/bioformats/blob/b1be2a9baa7b780ca258315d80132479099c57de/components/formats-bsd/src/loci/formats/out/OMEXMLWriter.java#L106-L108

With the new API, a conversion workflow can read and convert the value of the `Creator` attribute. ON the other hand, capturing the version of the software which created the converted OME metadata is still valuable.

Listing a few options up for discussion:

1. give the user the option to either preserve or override the Creator attribute
2. always override the Creator attribute but store the previous Creator value as an annotation

**Comment by dgault** [comment]
Fixed in https://github.com/ome/bioformats/pull/3959
