### ISSUE TITLE
ArrayIndexOutOfBoundsException from DeltavisionReader.initExtraMetadata with v6.5.1

### ISSUE THREAD

**Issue by mtbc** [ome/bioformats#3601]
See [QA 29449](https://www.openmicroscopy.org/qa2/qa/feedback/29449/) and [showinf.log](https://github.com/ome/bioformats/files/5000269/showinf.log).

**Comment by dgault** [comment]
For my own future reference, the exception is being thrown at line https://github.com/ome/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/DeltavisionReader.java#L923
