### ISSUE TITLE
CZI: Request for different fill values for empty tiles 

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3614]
This request was raised in forum thread: https://forum.image.sc/t/pyramidal-czi-images-and-the-color-of-unscanned-regions/42624

For brightfield images such as in the thread or in QA-10431 (as a random example), the original image uses the value 255 for unscanned regions but Bio-Formats is also setting empty tiles to 0. Having this original fill value (https://github.com/ome/bioformats/blob/8a2da344ba7845118a293d1241fc3f90ba493ebb/components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java#L344) be configurable or vary depending on the image type would be beneficial for examples such as in the thread.

**Comment by melissalinkert** [comment]
https://github.com/ome/bioformats/pull/3795 introduced a fill value of 255 for brightfield data. This was included in 6.9.1.

#3800 is the follow-up issue for more generic fill value configuration.
