### ISSUE TITLE
DICOM: Reader stops decoding DICOM attributes at first PixelData (7FE0,0010) occurence and begin reading image bytes

### ISSUE THREAD

**Issue by ballaminut** [ome/bioformats#3622]
When an image has more PixelData (7FE0,0010) DICOM attributes (for example the one containing the image bytes and one inside IconImageSequence (0088,0200)), DicomReader stops decoding DICOM attributes after the first occurrence and from that point it starts reading image bytes.

This behavior is due to PIXEL_DATA case in tag switch (line 645)

          break;
        case PIXEL_DATA:
        case ITEM:
        case 0xffee000:
          if (elementLength != 0) {
            baseOffset = in.getFilePointer();
            addInfo(tag, location);
            decodingTags = false;
          }
          else addInfo(tag, null);
          break;

I do not know if image pixel bytes are the last occurrence of PixelData (7FE0,0010); if so, a possible patch could be

          break;
        case PIXEL_DATA:
          if (elementLength != 0) {
            baseOffset = in.getFilePointer();
            in.skipBytes(elementLength);
          }
          else addInfo(tag, null);
          break;
        case ITEM:
        case 0xffee000:
          if (elementLength != 0) {
            baseOffset = in.getFilePointer();
            addInfo(tag, location);
            decodingTags = false;
          }
          else addInfo(tag, null);
          break;

Attached a sample image.

[002_2394x3062x1_16bit_1.2.840.10008.1.2_InnerPixelData.dcm.zip](https://github.com/ome/bioformats/files/5379584/002_2394x3062x1_16bit_1.2.840.10008.1.2_InnerPixelData.dcm.zip)

**Comment by melissalinkert** [comment]
This appears to be fixed with 6.8.0, which substantially changed the DICOM reader. Feel free to reopen if you still see problems after upgrading.
