### ISSUE TITLE
SimplePCI: CXD files missing field date time

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3625]
This issue was raised on imagesc thread https://forum.image.sc/t/cxd-simplepci-missing-metadata-fields/44227 and a sample file has been provided which reproduces the behaviour in Bio-Formats 6.5.1

Usually the metadata fields are present in the file as below:
```
|File Info First Field Date  Time|1.3196792353483E10|
|File Info Last Field Date  Time|1.3196792358730999E10|
```

With recent versions of the files from newer Hamamatsu HCImage software the fields are not present. However it is possible to see the values in the proprietary software suggesting the metadata is still present. I have attempted to locate a suitable metadata field which is not getting parsed but so far have not managed to locate the correct entry.

**Comment by melissalinkert** [comment]
Using 6.8.0, this file seems to have timestamps parsed that match HCImage.  The original metadata keys are different (```Field n Time_From_Start``` and ```Field n Time_From_Last```), but both ```Pixels.TimeIncrement``` and ```Plane.DeltaT``` are present in the OME-XML.  See https://github.com/openmicroscopy/data_repo_config/pull/510
