### ISSUE TITLE
VSI: incorrect exposure times

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3642]
This issue was raised in forum thread https://forum.image.sc/t/bio-formats-exposure-time-incorrect-when-importing-vsi-files/46080

In the OME-XML the Exposure Time is the same for each plane. However the correct values can be found in the original metadata tags as shown in the images attached in the imagesc thread.

**Comment by melissalinkert** [comment]
https://trello.com/c/v47N2hGC/382-vsi-incorrect-metadata-posz-and-exp-time might be related.

**Comment by dgault** [comment]
A sample file showing the issue has been received in QA-29751 and the issue was tested and reproduced with BF 6.5.1

In the OME-XML the exposure time remains the same across planes:
```
<Plane ExposureTime="1.0" ExposureTimeUnit="s" PositionX="-82449.09870917775" PositionXUnit="µm" PositionY="-68454.64727965342" PositionYUnit="µm" TheC="0" TheT="0" TheZ="0"/>
<Plane ExposureTime="1.0" ExposureTimeUnit="s" PositionX="-82449.09870917775" PositionXUnit="µm" PositionY="-68454.64727965342" PositionYUnit="µm" TheC="1" TheT="0" TheZ="0"/>
<Plane ExposureTime="1.0" ExposureTimeUnit="s" PositionX="-82449.09870917775" PositionXUnit="µm" PositionY="-68454.64727965342" PositionYUnit="µm" TheC="2" TheT="0" TheZ="0"/>
```

In the original metadata the correct values are present:
```
Microscope Exposure time (microseconds) #1	150000
Microscope Exposure time (microseconds) #2	250000
Microscope Exposure time (microseconds) #3	1000000
```
