### ISSUE TITLE
Add support for sbx files (neurolabware 2p microscope output data)

### ISSUE THREAD

**Issue by orena1** [ome/bioformats#3666]
Hi,
This is the website of the microscope:
http://neurolabware.com/
there is a dedicated section for the software:
https://scanbox.org/

There is a great python implementation here:
https://github.com/jcouto/sbxreader

Thanks!

**Comment by dgault** [comment]
Hi @orena1, thank you for your interest in adding support for this format. Our position on adding new formats currently is better outlined in our blog post (https://blog.openmicroscopy.org/community/file-formats/2019/06/25/formats/ 8).

We have had companies such as 3i, who have taken over support of their own file format and other companies have added support for their format either by contributing directly to the library or by commissioning Glencoe Software to do so. Where necessary, the open source team has added support for formats that are needed for their funded priorities like datasets published in the Image Data Resource.
