### ISSUE TITLE
SVS: handle optional label and macro images

### ISSUE THREAD

**Issue by sbesson** [ome/bioformats#3682]
See https://forum.image.sc/t/correct-way-to-convert-svs-slides-for-omero-import/50942/.

As described in the `Digital Slides and Third-Party Data Interchange`, a SVS file may contain a label and/or a macro image. In the majority of the samples, these images are typically tagged with the SubFileType 0x1 and 0x9 although this is not part of the document above. 

While other translational libraries like `openslide` and `tifffile` handle this optional presence, the current version of the SVSReader contains some assumptions that seem to unconditionally expect these ancillary images e.g.

https://github.com/ome/bioformats/blob/25645389e076a7bd0011e04c4dd8982c0f0614ed/components/formats-gpl/src/loci/formats/in/SVSReader.java#L331

https://forum.image.sc/t/correct-way-to-convert-svs-slides-for-omero-import/50942/13 and https://forum.image.sc/t/correct-way-to-convert-svs-slides-for-omero-import/50942/19 describe how to generate a secondary SVS file from public samples illustrating this use case.

From a quick search across our curated QA repository and the OpenSlide public samples, I  found no original SVS file without a label or a macro image but it might be useful to  look further for additional representative samples.

**Comment by MITEL-UNIUD** [comment]
Yesterday I was browsing throught SVSreader.java to find where macro and label were managed, and there are a couple of areas:
- https://github.com/ome/bioformats/blob/25645389e076a7bd0011e04c4dd8982c0f0614ed/components/formats-gpl/src/loci/formats/in/SVSReader.java#L334 (look at the comment in the `else` branch)
- https://github.com/ome/bioformats/blob/25645389e076a7bd0011e04c4dd8982c0f0614ed/components/formats-gpl/src/loci/formats/in/SVSReader.java#L475  (again, in the `else` branch there is the case of pyramid levels without macro/label). 

Regarding the availability of examples, by default both macro and label are saved. However, looking at the manual, there is a Scanscope system property `DoLabelCapture` that sets whether the label is captured or not. As soon as I can go to the scanner place, I will try to acquire an example at least without label.

**Comment by sbesson** [comment]
As mentioned in https://github.com/ome/bioformats/pull/4081#issue-1847338429, I could not reproduce this issue anymore with Bio-Formats 7.0.0. Looking at the reader itself, I suspect the relevant changes fully relaxing the assumptions in terms of label/macro images were introduced https://github.com/ome/bioformats/commit/cc1112f3a9d2b5ec044a950695cfd7200812e080 and have been released in Bio-Formats 6.8.0.
