### ISSUE TITLE
Relicense JHDFService (and possibly CellH5Reader/Writer)

### ISSUE THREAD

**Issue by sbesson** [ome/bioformats#3696]
The reader for the BigDataViewer file format was introduced in https://github.com/ome/bioformats/pull/3151 in the context of the academic BBSRC BB/P027032/1 grant. Given the funding, the provenance and the academic nature of the format, there is no rationale for having this format under the GPL-2 license and the @ome/formats team has discussed relicensing it under the permissive BSD 2-clause license.

To access the HDF5 binary data, this reader depends on the JHDF service, also licensed as GPL-2, introduced as part of the work adding support for the CellH5 file format - see https://github.com/ome/bioformats/pull/1637, 

@sommerc as the original author and primary contributor, would you be willing to relicense these classes under the more permissive BSD-2 clause?

-  components/formats-gpl/src/loci/formats/services/JHDFService.java
- components/formats-gpl/test/loci/formats/utests/JHDFServiceTest.java
- components/formats-gpl/src/loci/formats/services/JHDFServiceImpl.java
- components/formats-gpl/test/loci/formats/utests/MissingJHDFServiceTest.java

If so, an addition proposal would be to also re-license the CellH5 reader and writer using the same permissive license to facilitate their usage as widely as possible.

/cc @melissalinkert

**Comment by sommerc** [comment]
Absolutely! This makes perfect sense for both. 

Cheers, Chris

**Comment by sbesson** [comment]
Fantastic, thanks @sommerc for getting back to us. Looking at the contributor list for the concerned files, the only other two authors are @melissalinkert and myself.  

I authorize my contributions to the JHDFServiceImpl.java to be relicensed as BSD-2.

Mostly for bookkeeping purposes, @melissalinkert I assume there is no objection from your side?
