### ISSUE TITLE
How to make OMERO server render a new image?

### ISSUE THREAD

**Issue by r0ach0** [ome/bioformats#3716]
I'm trying to add a new format reader to bioformats.
the reader works fine until images are uploaded to omero server.
omero.insight shows first and preview images.

but, in image viewer, no function effects on the image: z and t dimension scrolls, channel on/off buttons, color range.

when i toggle channel button, the image turns black, and never comes back even though i toggle it again
funny thing is, projection works fine through z and t dimensions.

i think openBytes() works pretty fine.
what do you think is the problem?

In imageJ, hyperstack view makes "Invalid Index C" or "Invalid plane index" exceptions

![Screenshot 2021-07-19 152459](https://user-images.githubusercontent.com/45354796/126112870-df574ee9-d3dd-4072-bf53-1c8d18bfd42a.png)

**Comment by dgault** [comment]
Hi @r0ach0, is your new reader in its own jar or is it built with Bio-Formats? Have you included the reader with Insight and the OMERO Server?

**Comment by r0ach0** [comment]
> Hi @r0ach0, is your new reader in its own jar or is it built with Bio-Formats? Have you included the reader with Insight and the OMERO Server?

Yes. I replaced bioformats-gpl-[VERSION].jar in Insight/app/lib, server/lib/client, server/lib/server.

**Comment by joshmoore** [comment]
@r0ach0 : can I ask that you please stop deleting the content of the questions you ask us? We're willing to help for free only because those questions & answers help others.
