### ISSUE TITLE
bfconvert `-overwrite` option is ignored while converting to several output images

### ISSUE THREAD

**Issue by lucassus** [ome/bioformats#3746]
For instance such command works fine:

```
> bfconvert fixtures/images/lif1.lif output/lif1.ome.tiff
Output file output/lif1.ome.tiff exists.
Do you want to overwrite it? ([y]/n)
```

`bfconvert` correctly warns warns me about existing file.

But on the other hand, when I'm trying, for example extract separate per-serie images, like:

`bfconvert fixtures/images/lif1.lif output/lif1_%s.ome.tiff`

the first run is  perfectly fine, but the second run does not give any confirmation. Moreover, it seems that `-overwrite` and `-nooverwrite` options have no effect. And, here is the weirdest part, it seems that `bfconvert` appends data to the already existing files, e.g.:

1. Directory listing from the first run:
```
➜ ll -h output
total 41640
drwxr-xr-x   4 lucassus  staff   128B 13 Nov 11:21 .
drwxr-xr-x  83 lucassus  staff   2.6K 13 Nov 11:21 ..
-rw-r--r--   1 lucassus  staff    15M 13 Nov 11:22 lif1_0.ome.tiff
-rw-r--r--   1 lucassus  staff   4.3M 13 Nov 11:22 lif1_1.ome.tiff
```

2. ...and from the second run
```
total 79056
drwxr-xr-x   4 lucassus  staff   128B 13 Nov 11:21 .
drwxr-xr-x  83 lucassus  staff   2.6K 13 Nov 11:21 ..
-rw-r--r--   1 lucassus  staff    29M 13 Nov 11:22 lif1_0.ome.tiff
-rw-r--r--   1 lucassus  staff   8.3M 13 Nov 11:22 lif1_1.ome.tiff
```

The output files are doubled in size.

I believe that in case of multi-file conversion bftools should override destination files or exit with an error.

**Comment by dgault** [comment]
Thanks @lucassus for raising the issue, I was able to test and confirm the same results as you are seeing with the lastest Bio-Formats release (6.7.0). This is a bug in the bfconvert tool that will impact any use of the various pattern file options in the output name.
