### ISSUE TITLE
Maven deploy running in forked repositories and failing the build

### ISSUE THREAD

**Issue by rleigh-codelibre** [ome/bioformats#3798]
Example: [rleigh-codelibre/bioformats CI build](https://github.com/rleigh-codelibre/bioformats/runs/5614623710?check_suite_focus=true)

Please could you disable this if not running in the context of the `ome/bioformats` repository, so forks of the primary repository won't fail their CI builds?

Thanks,
Roger

**Comment by sbesson** [comment]
I have also run into this behavior and the false positive noise is amplified by the fact that the Maven workflow runs weekly. #3799 should address the issue
