### ISSUE TITLE
Memoizer API updates

### ISSUE THREAD

**Issue by melissalinkert** [ome/bioformats#3820]
See https://github.com/glencoesoftware/bioformats2raw/pull/145#issuecomment-1117116897

**Comment by sbesson** [comment]
Looking at https://github.com/glencoesoftware/bioformats2raw/blob/ac99da5b4fa6a8e28a4a52d3c88474f3fd22b122/src/main/java/com/glencoesoftware/bioformats2raw/Converter.java#L723-L740, a few thoughts:

- should https://github.com/ome/bioformats/blob/6ef3227738e0febb4f6eaafdf1942318bd40970c/components/formats-bsd/src/loci/formats/Memoizer.java#L508-L512 be updated to support `null` reader input? All other constructors could be delegate to this single implementation.
- do we need a `public Memoizer(IFormatReader r, File directory)` constructor?
