### ISSUE TITLE
ND2: Image stack lost for image with small dimensions

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3838]
Issue was raised on forum thread https://forum.image.sc/t/can-not-read-nd2-image-stack-when-image-dimension-is-small/68155 but no sample file reproducing the issue is available as of yet.

The issue reports that when opening an image stack (in this case 5 planes) with a small image (50 x 50) then the image stack is lost and only a single plane is displayed. The same issue does not occur if the image is slightly larger (100 x 106). This was reported with Bio-Formats 6.10.0.

**Comment by denglabpku** [comment]
Hi Gault, Here is Zuhui.
I uploaded the ND2 file for your testing. Please remove the PNG suffix, because I found ND2 is not supported to upload.

![small_test nd2](https://user-images.githubusercontent.com/105469836/173719876-81f73300-9c5d-4a33-ad6e-793a4675899c.png)

**Comment by melissalinkert** [comment]
As noted in https://github.com/ome/bioformats/pull/3863, a temporary solution to this problem is to set the `nativend2.chunkmap` option to `false` as described here:

https://docs.openmicroscopy.org/bio-formats/6.9.1/formats/options.html#usage

**Comment by Borease** [comment]
> As noted in #3863, a temporary solution to this problem is to set the `nativend2.chunkmap` option to `false` as described here:
> 
> https://docs.openmicroscopy.org/bio-formats/6.9.1/formats/options.html#usage

Hi  melissalinkert

Thank you for your help. I can open the file correctly right now.
