### ISSUE TITLE
OME-TIFF saving differently on windows vs linux?

### ISSUE THREAD

**Issue by noamza** [ome/bioformats#3840]
I am trying to debug an issue and I noticed another python module that I am using (https://pypi.org/project/scanimage-tiff-reader/), only throws errors on OME-TIFFs that I save through ImageJ(1.53q) running on ubuntu linux, but not when I save them using ImageJ(1.52p) running on windows. Now I am not sure if this is because the ImageJ versions are different or if it's because one is running on windows and one is on linux, but if you have any insight into this I would greatly appreciate it.
Thanks you

**Comment by sbesson** [comment]
@noamza do you have public samples of typical files (ideally from the same source) saved under both systems that you could share either in this issue if it's small enough or by uploading them to https://zenodo.org/  ?

**Comment by melissalinkert** [comment]
Closing, as we haven't received a test case for this in over 2 years, and aren't aware of any expected differences in writing OME-TIFF on Linux vs Windows.

Please do re-open though if this is still a concern with Bio-Formats 8.0.0, with as much detail as possible (per https://github.com/ome/bioformats/issues/3840#issuecomment-1163199337) and the specific errors that occur when opening.
