### ISSUE TITLE
Zeiss CZI: Line scans missing data

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3881]
Issue was raised by a user of forum thread https://forum.image.sc/t/line-scans-with-many-time-points-drop-97-of-data-zeiss-microscope/72044

A sample file that reproduces the issue was provided and testing using the latest Bio-Formats 6.10.1 displays the problem as described. The majority of the line scans in the file display as zero with no data showing, this is not the case when the file is read with Zen.

**Comment by melissalinkert** [comment]
Maybe related to https://github.com/ome/bioformats/issues/3525?

**Comment by dgault** [comment]
Yeah they do look likely to be the same issue, closing this as a duplicate and migrating the comments to the original issue
