### ISSUE TITLE
Ventana BIF: grid of zero pixel values at lowest resolution levels

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3927]
This issue was raised on 2 separate forum threads:
https://forum.image.sc/t/ventana-bif-images-imported-to-omero-web-do-not-stitch-together/75002/4
https://forum.image.sc/t/bif-opened-with-bioformats-contains-black-lines-on-the-highest-overview-levels/75221

Sample files from the first thread have been tested with BF 6.11.1 and will be copied to inbox shortly. With those datasets the lowest resolution level shows a grid of zero pixel values across the image.

<img width="434" alt="Screenshot 2023-01-04 at 15 26 35" src="https://user-images.githubusercontent.com/1628865/210589633-f12e2ac8-7d0e-4e32-9b1e-8bc197f8dec2.png">

The second thread reports that it the issue can also be seen in other resolution levels (usually 0-4) but is file dependant.

**Comment by vs-jpineda** [comment]
Weird behavior.

This bug does not appear using omero.insight to visualize the image, but does on omero.web
