### ISSUE TITLE
c++ source code on git?

### ISSUE THREAD

**Issue by jackyko1991** [ome/bioformats#3968]
The package has been developed to offer a seamless Java and Python interface. While I appreciate its usefulness for my ongoing projects, which are in C++, I would like to leverage the OME-bioformats tool for input/output operations.

I noticed that the source code and pre-built libraries are accessible through the following website: https://downloads.openmicroscopy.org/bio-formats-cpp/5.1.8/. However, I'm interested in keeping track of changes and contributing to the C++ side. For example, re-compiling and testing the package on newer versions of Windows and MSVC is necessary to ensure it meets the package requirements of other libraries. This is often the case for NVidia Windows packages with dedicated MSVC versions.

To facilitate this process, I would like to manage the C++ source code with git. While the website directs me to a repository, I'm unable to locate the specific cpp folder. It was previously available in the older version of the repository.

Any reason why the cpp source code is removed here?

**Comment by dgault** [comment]
Hi @jackyko1991, the Bio-Formats CPP package was split out of the main repository and renamed to OME-Files. OME Files provided a reference implementation of the OME Data Model and OME-TIFF file format. The OME-Files repo was archived in 2019 (https://github.com/ome/ome-files-cpp) and further development of that project occurred independently at https://gitlab.com/codelibre/ome/ome-files

**Comment by melissalinkert** [comment]
Closing, as https://github.com/ome/bioformats/issues/3968#issuecomment-1482776464 represents the current state of C++ repos and no additional work on that code is planned. Feel free to re-open if there are any further questions.
