### ISSUE TITLE
Label and Macro images are incorrected indexed since 6.8.0

### ISSUE THREAD

**Issue by jamescooper-gd** [ome/bioformats#3986]
Since https://github.com/ome/bioformats/commit/cc1112f3a9d2b5ec044a950695cfd7200812e080 the label image index and the macro image index are inverted.  

Using an example from https://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/ with QuPath, we observe that when using open slide the label and macro are correct, but when using bio-formats, they're inverted.

![open-slide](https://user-images.githubusercontent.com/5167540/234615741-f1f690be-9932-4b49-a127-6983a052067d.jpg)
![bio-formats](https://user-images.githubusercontent.com/5167540/234615753-46b23f9b-644f-4744-8c0d-63d5c3017da4.jpg)

**Comment by dgault** [comment]
Thanks @jamescooper-gd for raising the issue, I can reproduce the bug using the [CMU-1.svs](https://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1.svs) sample file you linked with the latest Bio-Formats release (6.12.0).
