### ISSUE TITLE
AFI / SVS: getMagnification results in NullPointerException

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#4036]
This issue was raised on forum thread https://forum.image.sc/t/error-uploading-afi-image/81073

The original thread was due to failures with an afi file-set. However the exception appears to be in the underlying SVSReader and can be reproduced using Bio-Formats 6.13.0. The exception doesn't occur if you just read the SVS file directly, only as part of the AFI.

It looks as though the SVSReader initializes magnification to null as a Double, when the AFIReader calls getMagnification (returns a primitive double) and no magnification is set, then an NPE is thrown.

```
Exception in thread "main" java.lang.NullPointerException
	at loci.formats.in.SVSReader.getMagnification(SVSReader.java:635)
	at loci.formats.in.AFIReader.initFile(AFIReader.java:334)
	at loci.formats.FormatReader.setId(FormatReader.java:1466)
```

**Comment by melissalinkert** [comment]
Is the problematic dataset available anywhere? I didn't see anything relevant under `inbox/`.

**Comment by dgault** [comment]
Should now be available on scratch/inbox/imagesc-81073
