### ISSUE TITLE
CZI: Wrong dimensions

### ISSUE THREAD

**Issue by dominikl** [ome/bioformats#4084]
If you import the image from [QA 33776](https://www.openmicroscopy.org/qa2/qa/feedback/33776/) - ignore the error message on the QA, the image does import with latest version - the image dimensions look very wrong:
![Screenshot 2023-08-17 at 10 01 31](https://github.com/ome/bioformats/assets/6575139/db34b84b-ea1f-4269-9549-a84fa7195498)

Something's got mixed there.

Latest bftools shows the same:
```
        Image count = 409840
        RGB = false (1)
        Interleaved = false
        Indexed = true (false color)
        Width = 128
        Height = 1
        SizeZ = 1
        SizeT = 204920
        SizeC = 2
        Tile size = 128 x 1
        Thumbnail size = 128 x 1
        Endianness = intel (little)
        Dimension order = XYCZT (certain)
        Pixel type = uint16
        Valid bits per pixel = 16
        Metadata complete = false
        Thumbnail series = false
```

**Comment by melissalinkert** [comment]
This is an XT scan; while initially suspicious, the dimensions are in fact correct as confirmed by ZEN. https://github.com/openmicroscopy/data_repo_config/pull/592 adds the file to the test repo.

**Comment by dominikl** [comment]
Ah, thanks @melissalinkert 👍  didn't know.
