### ISSUE TITLE
ZeissCZIReader get lut error

### ISSUE THREAD

**Issue by SinnoSong** [ome/bioformats#4087]
I have a `czi` file , read color of one channel , the color is `#FF0000FF`, in the source code `get16Lut` method is used int to parse this number.

**Comment by joshmoore** [comment]
Hi @SinnoSong. Sorry, I'm not understanding your question. Can you share more about what you're trying to do? What tool are you using? Or are you writing your own code? If so, can you share it? What is the entire error that you are getting?

**Comment by SinnoSong** [comment]
@joshmoore Sorry, I use `formats-gpl` to read a `czi` file. The file has 2 channels, the color of a channel is `#FF0000FF`. When I use `get16BitLookupTable` method to get Lut, the method throws `NumberFormatException`. I see the `get16BitLookupTable` method use `int colorValue = Integer.parseInt(color, 16);` to convert `FF0000FF` to a integer number, but `FF0000FF` is greater than Integer max value. How can I get Lut of this channel?
