### ISSUE TITLE
Loading 64-bit int TIFFs

### ISSUE THREAD

**Issue by edwardando** [ome/bioformats#4089]
Dear all,
As a Fiji user I'm a long time user and appreciator of BioFormats.
However... there appears to be quite dangerous behaviour when loading 64-bit int or uint tiffs, as I posted here:

https://forum.image.sc/t/saving-and-loading-64-bit-int-tiffs/85523

@cgohlke proposes a very reasonable solution, and I'd be interested in your opinion

**Comment by dgault** [comment]
Thanks @edwardando for opening the issue, hopefully this will be something we can improve in a future release, the suggested fix (copied below) seems like a sensible option in this case. 

```
The fix will probably be to throw an UnknownFormatException if BitsPerSample==64 and SampleFormat!=3.
```

**Comment by edwardando** [comment]
Fully agreed, thanks!
