### ISSUE TITLE
#4090 breaks support for Apple Silicon for formats that don't need TurboJPEG

### ISSUE THREAD

**Issue by petebankhead** [ome/bioformats#4109]
Hi,

https://github.com/ome/bioformats/pull/4090 seems to break the use of
```java
ImageReader reader = new ImageReader();
```
on Apple Silicon - even for formats that otherwise worked without problem (e.g. CMU-1.svs, LuCa tiff images).

The issue seems to be that the `try/catch` block doesn't handle the `RuntimeException` thrown whenever it is not possible to load TurboJPEG:
https://github.com/ome/bioformats/blob/e484e1faefd6c7590fa5dbb56e56f3cc360d9139/components/formats-api/src/loci/formats/ImageReader.java#L134-L139

The workaround is to pass a `ClassList` that has been already been checked to exclude classes that can't be instantiated, e.g. using
```java
        private static ClassList<IFormatReader> getDefaultClassList() {
		ClassList<IFormatReader> classes = new ClassList<>(IFormatReader.class);
		for (var cls : ImageReader.getDefaultReaderClasses().getClasses()) {
			try {
				var instance = cls.getConstructor().newInstance();
				if (instance != null)
					classes.addClass(cls);
			} catch (Throwable t) {
				logger.debug("Cannot instantiate reader class " + cls.getName() + ": " + t.getMessage());
			}
		}
		return classes;
	}

...

ImageReader reader = new ImageReader(getDefaultClassList());
```

Adding code like this should be enough for us to be able to include 7.0.1 in QuPath - but since Bio-Formats is the now only dependency we have without Apple Silicon support, it would be even better if https://github.com/ome/bioformats/issues/3756 and https://github.com/ome/bioformats/issues/3858 could be addressed :) The QuPath Apple Silicon builds are now faster and more reliable on M1/M2 Macs (due in part to some OpenCV changes), so will be recommended with the caveat that most .czi images won't work.

**Comment by dgault** [comment]
Thanks @petebankhead for raising this issue, we will look at resolving this for the next release.

**Comment by CGDogan** [comment]
For QuPath, you can remove the need for Rosetta by simply following the steps in #4042 or just copying the binary. Once you compile it with the steps I've given on any Mac computer or copy my binary, all you need to do is to unzip the bioformats-package.jar, copy the turbojpeg binary in the correct new folder, then rezip it (you need a zip tool, java's jar tool won't work) Needless to say, you would then need to distribute the turbojpeg source code to comply with GPL. I use this without problems on my Apple Silicon. I'm sure QuPath users would find it useful meanwhile.
