### ISSUE TITLE
Repeated conditional test II

### ISSUE THREAD

**Issue by scuniff** [ome/bioformats#4160]
Regarding:

https://github.com/scifio/bioformats/blob/6bcf6b9d284686416f3458c8893fbcf4ebcdecfd/components/forks/poi/src/loci/poi/hssf/record/SSTRecord.java#L455

Should it be:

if (bucketAbsoluteOffsets == null || bucket**Relative**Offsets == null)

**Comment by sbesson** [comment]
This fork has been removed from the Bio-Formats code base on the development line. Additionally the commit points to a fork. Closing as invalid
