### ISSUE TITLE
Strings are being compared with == and !=

### ISSUE THREAD

**Issue by scuniff** [ome/bioformats#4184]
2 occurrences where 2 Strings are being compared with == and !=.

They should be using String.equals()

https://github.com/ome/bioformats/blob/6fa35f6deb652ac34e3bb2fba5b8b694481d3585/components/formats-bsd/src/loci/formats/gui/PreviewPane.java#L218

https://github.com/ome/bioformats/blob/6fa35f6deb652ac34e3bb2fba5b8b694481d3585/components/formats-bsd/src/loci/formats/gui/PreviewPane.java#L263

should be?

Line 218 if (id.equals(lastId)) continue;
Line 263 if (!id.equals(loadId)) {

**Comment by joshmoore** [comment]
Thanks, as ever, @scuniff
