### ISSUE TITLE
Switch clauses have same code

### ISSUE THREAD

**Issue by scuniff** [ome/bioformats#4213]
As wanted??

https://github.com/ome/bioformats/blob/682bc7e318b88f159d3c6e2603fb82fb9d613268/components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java#L2128-L2143

**Comment by dgault** [comment]
Thank you for opening the issue @scuniff, in this case the switch clauses are meant to have the same code. These could be combined into a single case statement to reduce the duplication but for readability the current code also works well.
