### ISSUE TITLE
unable to open the images saved as qpproj

### ISSUE THREAD

**Issue by 7Lechen322** [ome/bioformats#4247]
images in ndpis and ndpi format cannot be opened when saved as qpproj, it said they are removed or deleted but they are not. when click the image, there is a window showing that error attempting to load image data, unavle to build image server for file...with requested provider qupath.lib.images.bioformates.Bioformatsserverbuilder. What should i do for this?

**Comment by melissalinkert** [comment]
@7Lechen322 : questions and issues with using QuPath should be reported on [forum.image.sc](forum.image.sc) as indicated in the [QuPath documentation](https://qupath.readthedocs.io/en/stable/docs/starting/help.html). There are several reasons why you might see an error when opening a .qpproj file, many of which are not related to Bio-Formats itself - [this section of the QuPath documentation](https://qupath.readthedocs.io/en/stable/docs/tutorials/projects.html#fix-paths) may be helpful.
