### ISSUE TITLE
showinf image viewer broken since 8.0.0 (on OSX at least)

### ISSUE THREAD

**Issue by dominikl** [ome/bioformats#4251]
Installed  7.3.0 via conda:
`conda install -c ome  bftools=7.3.0`
Ran: `showinf <some image>` works as expected.

Update to 8.0.0, then again:
`showinf <some image>` Shows the metadata like expected, the image viewer very briefly pops up and crashes.
Unfortunately there's no additional info, even with `-debug` flag.

**Comment by sbesson** [comment]
Should be fixed by https://github.com/ome/bioformats/pull/4250 in the upcoming patch release of Bio-Formats

**Comment by dominikl** [comment]
Ah sorry, missed that.

**Comment by sbesson** [comment]
No problem. I am going to mark this as resolved as per the issue above but the Conda package should definitely be retested post 8.0.1 release
